services:
  postgres_dev:
    container_name: "postgres-development"
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"
    networks:
      - postgres


  pgadmin_dev:
    container_name: pgadmin-dev
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres_dev
    networks:
      - postgres


networks:
  postgres:
    driver: bridge