openapi: 3.0.3
info:
  title: Inventarisierungsmanagment API
  description: API für das managen der Inventarisierungliste
  version: 1.0.0
servers:
- url: insy.hs-esslingen.de
paths:
  /inv-list:
    get:
      tags:
      - Inventarisierungsliste
      summary: Ruft alle Elemente in der Inventarisierunsliste ab
      responses:
        "200":
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        "204":
          description: No content found
        "500":
          description: Internal server error
  /inv-list/{id}:
    get:
      tags:
      - Inventarisierungsliste
      summary: Detailansicht eines Gegenstands in der Liste
      description: Ruft genauere Informationen zu Gegenstand an
      parameters:
      - name: id
        in: path
        description: ID des Gegenstands
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Erfolgreiches Abrufen des Gegenstandes
        "400":
          description: Gegenstand zu ID konnte nicht gefunden werden
        "500":
          description: Interner Fehler beim Abrufen des Gegenstands
    delete:
      tags:
      - Inventarisierungsliste
      summary: Löscht Gegenstände aus der Inventarisierungsliste.
      description: Löscht Gegenstände.
      operationId: deleteItem
      parameters:
      - name: id
        in: path
        description: ID des Gegenstands zum löschen
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Gegenstand wurde erfolgreich gelöscht
        "400":
          description: Ungülitger Artikelwert
        "500":
          description: Interner Serverfehler
  /inv:
    post:
      tags:
      - Inventarisierung
      summary: Manuelles Inventarisieren eines neuen Gegenstandes (nicht über Wizard).
      description: Neues Gerät inventarisieren.
      operationId: addInv
      requestBody:
        description: Neues Gerät inventarisieren
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        "200":
          description: Gerät wurde inventarisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        "400":
          description: Falsche Eingabeparameter
        "500":
          description: Interner Fehler beim Inventarisieren
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /new-inv:
    get:
      tags:
      - Inventarisierung
      summary: Ruft Liste noch nicht inventarisierte Gegenstände ab
      responses:
        "200":
          description: Liste mit allen noch nicht inventarisierten Gegenständen
        "204":
          description: Keine Elemente zum inventarisieren gefunden
        "500":
          description: Interner Serverfehler
  /new-inv/{id}:
    get:
      tags:
      - Inventarisierung
      summary: Ruft einzelnen Gegenstand zum Inventarisieren ab
      parameters:
      - name: id
        in: path
        description: ID des Gegenstands
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Öffnen des Inventariserungswizard für den neuen Gegenstand
        "500":
          description: Interner Serverfehler beim Abrufen des Gegenstandes
    post:
      tags:
      - Inventarisierung
      summary: Schickt Gegenstand am Ende des Inventarisierungswizards zum Inventarisieren an das Backend
      parameters:
      - name: id
        in: path
        description: ID des Gegenstands
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "201":
          description: Gegenstand wurde erfolgreich hinzugefügt
        "400":
          description: Gegenstand konnte aufgrund fehlender/falscher Attribute nicht inventarisiert werden
        "500":
          description: Interner Fehler beim Inventarisieren
    delete:
      tags:
      - Inventarisierung
      summary: Löscht Gegenstände aus der Liste der zu inventarisierenden Gegenstände
      parameters:
      - name: id
        in: path
        description: ID des Gegenstands
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Gegenstand wurde erfolgreich entfernt
        "500":
          description: Gegenstand konnte aufgrund eines internen Fehlers nicht gelöscht werden
  /inv-list/filter:
    get:
      tags:
      - Filter
      summary: Finde Gegenstände mit Hilfe von Filtern
      description: "Mehrere Filter können mit komma separiert werden zB. Filter1, Filter2."
      operationId: FilterItemsByTags
      parameters:
      - name: tags
        in: query
        description: Filterfunktion
        required: false
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Erfolgreicht gefiltert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        "400":
          description: Invalider Filter
        "500":
          description: Interner Serverfehler
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /inv-stats:
    get:
      tags:
      - Statistik
      summary: Statistik.
      description: Statistik für bestellte Produkte.
      operationId: findStats
      responses:
        "200":
          description: Erfolgreich angezeigt
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        "400":
          description: Invalid status value
        "500":
          description: Interner Fehler
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /import:
    get:
      tags:
      - Import/Export von Dateien
      summary: Ruft Seite zum Importieren von Excel-Listen ab
      responses:
        "200":
          description: Seite konnte erfolgreich abgerufen werden
        "500":
          description: Serverfehler beim Abrufen der Website
    post:
      tags:
      - Import/Export von Dateien
      summary: Schickt Excelliste zum Importieren an Backend
      description: Datei muss für Umwandlung passendes Format haben
      responses:
        "201":
          description: Daten wurden erfolgreich verarbeitet
        "400":
          description: Zu importierende Daten sind im falschen Format
        "500":
          description: Serverinterner Fehler beim umwandeln der Dateien
  /export:
    get:
      tags:
      - Import/Export von Dateien
      summary: Exportiert Inventarisierungsliste als Excel-Datei
      description: "Gesamte Liste kann ohne Parameter exportiert werden, mit Parametern werden nur einzelne Einträge exportiert"
      parameters:
      - name: ids
        in: query
        description: ID der Gegenstände bzw. range von - bis
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        "200":
          description: Excel-Liste wurde erfolgreich erstellt und zum Download bereitgestellt
        "500":
          description: Interner Fehler beim Erstellen der Excel-Liste
  /user/logout:
    get:
      tags:
      - user
      summary: Abmelden des derzeitigen Benutzers.
      description: Abmelden des Benutzers.
      operationId: logoutUser
      parameters: []
      responses:
        "200":
          description: Erfolgreich abgemeldet
        "500":
          description: Interner Serverfehler
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/login:
    get:
      tags:
      - user
      summary: Anmeldung des Benutzers.
      description: Anmeldung in das System.
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: Der Benutzername für das Login
        required: false
        schema:
          type: string
      - name: password
        in: query
        description: Das Password für das Login
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Erfolgreich angemeldet
        "400":
          description: Invalider Benutzername/Password angegeben
        "500":
          description: Interner Serverfehler
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Laptop
        description:
          type: string
          example: A powerful gaming laptop
        price:
          type: number
          format: float
          example: 1299.99
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
